//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAssmenit
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinup
    {
        public static IEnumerable<object> Sin_upEntities { get; internal set; }
        public int user_id1 { get; set; }
        public string Username { get; set; }
        public Nullable<int> Password_ { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Phone_number { get; set; }
        public string city { get; set; }
    }
}
